services:
  - type: web
    name: hsence
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/run_app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
